.TH GIF2HDF 1 "January 18, 2001"
.\" man page by Philippe Troin <phil@fifi.org>         -*- nroff -*-
.SH NAME
gif2hdf \- convert a GIF image to a HDF file
.SH SYNOPSIS
\fBgif2hdf\fP
\fIinput_hdf_file\fP
\fIoutput_gif_file\fP
.SH DESCRIPTION
\fBgif2hdf\fP converts a GIF image to a HDF file.
.SH "SEE ALSO"
\fBhdf\fP(5), \fBhdf2gif\fP(1)
