.TH HDF2GIF 1 "January 18, 2001"
.\" man page by Philippe Troin <phil@fifi.org>         -*- nroff -*-
.SH NAME
hdf2gif \- convert a HDF file to a GIF image
.SH SYNOPSIS
\fBhdf2gif\fP
\fIinput_gif_file\fP
\fIoutput_hdf_file\fP
.SH DESCRIPTION
\fBhdf2gif\fP converts a HDF file to a GIF image.
.SH NOTES
The output GIF is not compressed, and should not be encumbered by the
Unisys patent on LZW compression.
.SH "SEE ALSO"
\fBhdf\fP(5), \fBgif2hdf\fP(1)
