.TH HDF24TO8 1 "January 18, 2001"
.\" man page by Philippe Troin <phil@fifi.org>         -*- nroff -*-
.SH NAME
hdf24to8 \- convert an 24-bit image in an HDF file to a 8-bit image in another
HDF file
.SH SYNOPSIS
\fBhdf24to8\fP
\fIinput_hdf_file\fP
\fIoutput_hdf_file\fP
.SH DESCRIPTION
\fBhdf24to8\fP converts a 24-bit image in an HDF file into an 8-bit image in an
other HDF file.
.SH "SEE ALSO"
\fBhdf\fP(5), \fBhdf8to24\fP(1)
