.TH HDFUNPAC 1 "November 6, 1999"
.SH NAME
.ad l
.nh
hdfunpac \- unpacks an HDF file
.SH SYNOPSIS
.HP
\fBhdfunpac\fP
[\fB-d\fP <datafilename>] \fI<hdffile>\fP
.ad b
.hy
.SH DESCRIPTION
\fBhdfunpac\fP unpacks an HDF file by exporting the scientific
data elements (DFTAG_SD) to external object elements.  This is
a utility for external file handling for the parallel I/O interface
on the CM5.
