.\" man page by Jim Van Zandt <jrv@vanzandt.mv.com>         -*- nroff -*-
.TH JPEG2HDF 1 "November 5, 1999"
.SH NAME
jpeg2hdf \- convert JPEG images to HDF
.SH SYNOPSIS
\fBjpeg2hdf\fP \fIjpeg-file\fP \fIoutput-hdf-file\fP
.SH DESCRIPTION
\fBjpeg2hdf\fP reads an image from \fIjpeg-file\fP and converts it to
HDF format in \fIoutput-hdf-file\fP.
.SH "SEE ALSO"
\fBhdf2jpeg\fP(1), \fBhdf\fP(5)
